### ISSUE TITLE
Adaptive projected guidance (APG) node?

### ISSUE THREAD

**Issue by jepjoo** [asagi4/ComfyUI-Adaptive-Guidance#11]
Hi,

Some researchers have apparently developed a method that handles high CFG values much better. They call it adaptive projected guidance or APG. Do you think you could make a node that is like your AdaptiveGuider node but has APG instead of CFG? The code for APG is on page 22 of the paper:

https://arxiv.org/pdf/2410.02416

PS. thanks for AdaptiveGuider node, it's great with Flux, I use it quite a bit.

**Comment by asagi4** [comment]
Seems simple enough. I might take a look at it later tonight if I have time.

**Comment by asagi4** [comment]
I tried implementing it. 

I have no idea if it's correct though since I barely understand what is going on with diffusion math and figuring out what the paper is talking about and mapping that into tensors in ComfyUI is basically just somewhat advanced guesswork for me.

**Comment by asagi4** [comment]
If you want to test it, you'll need to check out the apg_test branch.

**Comment by Talae06** [comment]
It also has been implemented by [this node](https://github.com/MythicalChu/ComfyUI-APG_ImYourCFGNow) as mentioned in [this Reddit thread](https://www.reddit.com/r/StableDiffusion/comments/1fxbfzn/apg_instead_of_cfg_to_prevent_oversaturation/). I'll be interested to see compare with your version.
