### ISSUE TITLE
You may not have uploaded workflow yet? How do I get adaptive guidance running?

### ISSUE THREAD

**Issue by Ijustakid** [asagi4/ComfyUI-Adaptive-Guidance#6]
Same as the title.

Thanks.

**Comment by asagi4** [comment]
It's pretty simple. You just plug it in as a guider to a SamplerCustomAdvanced node

**Comment by asagi4** [comment]
I added an example workflow for comparing the node with basic guidance.

**Comment by Ijustakid** [comment]
It's great!

Thanks.
