### ISSUE TITLE
[Request] Allow for a 0.0001 step in threshold

### ISSUE THREAD

**Issue by Danamir** [asagi4/ComfyUI-Adaptive-Guidance#8]
I have some fringe cases where the Cosine similarity check needs to be tested against `0.9997` or such very high values. But the default step at `0.001` for the input prevent those. 

Would it be possible to alter the current input for `threshold` to add a decimal ? 

```Python
"threshold": ("FLOAT", {"default": 0.990, "min": 0.90, "max": 1.0, "step": 0.0001, "round": 0.0001}),
```

**Comment by asagi4** [comment]
I actually had the steps overridden in my comfybox workflow.

I wish ComfyUI's default UI allowed overriding or configuring the step values, sometimes they just get in the way.

**Comment by Danamir** [comment]
Thanks !
