### ISSUE TITLE
AdaptiveGuider gives different output than CFGGuider at CFG > 1, is this normal?

### ISSUE THREAD

**Issue by TermTo** [asagi4/ComfyUI-Adaptive-Guidance#9]
I thought AdaptiveGuider was simply adding CFG = 1 at the end steps and nothing else, but it turns out that it also gives different output than CFGGuider even before that, here's a comparison with AdaptiveGuider (threshold = 1 + uncond_zero_scale = 0 + cfg_start_pct = 0) and CFGGuider:

'A woman in Paris': https://imgsli.com/MjkwMjA0

Is there a way to add an option to have AdaptiveGuider to act exactly like CFGGuider when the threshold has not been reached? For example SkimmedCFG doesn't work on AdaptiveGuidance and works on CFGGuider due to those differences.

**Comment by asagi4** [comment]
Do you have a workflow to reproduce this? Because AdaptiveGuder *should* behave exactly as CFGGuider before the threshold is reached.

**Comment by asagi4** [comment]
I just tested using my example workflow and see no difference in the outputs. Are you sure you don't have a mistake in your workflow somewhere?

**Comment by TermTo** [comment]
> Do you have a workflow to reproduce this? Because AdaptiveGuder _should_ behave exactly as CFGGuider before the threshold is reached.
Sure thing, here's the output with CFGGuider: https://files.catbox.moe/rb358r.png
![a](https://github.com/user-attachments/assets/0d80b414-ac14-4329-81c6-fb50465e9937)

And here's the output with AdaptiveGuider (same settings): https://files.catbox.moe/7ooxks.png
![b](https://github.com/user-attachments/assets/23c83a03-42a2-48f7-8c7f-9fbcbe16b28b)

**Comment by TermTo** [comment]
> Does CFG even make sense with flux? As far as I understand it doesn't really work like other models.

It definitely does, CFG improves its prompt adherance if you use an Anti-CFG-burner like AutomaticCFG or Tonemap for example
https://reddit.com/r/StableDiffusion/comments/1eza71h/four_methods_to_run_flux_at_cfg_1/

> I have no idea what CFGGuider could be doing differently there though, since AdaptiveGuider should be doing the exact same thing it does when it's not active.

I see, there must be something in the code that triggers this different effect from CFGGuider, now the million dollar question is what that “something” might be.

**Comment by asagi4** [comment]
There's one thing I found that shouldn't affect anything, but maybe it does. Try the latest commit; If that isn't the issue, then I don't have any immediate ideas what might be going wrong.

My hardware is barely capable of running Flux, so if this doesn't fix it, debugging this is going to be torturous.

**Comment by TermTo** [comment]
> There's one thing I found that shouldn't affect anything, but maybe it does. Try the latest commit; If that isn't the issue, then I don't have any immediate ideas what might be going wrong.

No it's not working unfortunately

> My hardware is barely capable of running Flux, so if this doesn't fix it, debugging this is going to be torturous.

You don't need to go for the fp16 flux to do your tests, you can go for lower quants, you could even go for Q2_K, the only thing to measure here is the similarity between CFGGuider and AdaptiveGuider after all
https://github.com/city96/ComfyUI-GGUF
https://huggingface.co/city96/FLUX.1-dev-gguf/tree/main

**Comment by TermTo** [comment]
@asagi4 I think I found a way to make it work, you can look at my PR: https://github.com/asagi4/ComfyUI-Adaptive-Guidance/pull/10

**Comment by asagi4** [comment]
Bah, Github autoclosed this

**Comment by asagi4** [comment]
I think the latest commit fixes the difference. Testing is annoying because it takes me like 8 seconds per step to run your workflow even with quantization :P 

I think I'll take a look and see if I can refactor the code a bit...

**Comment by TermTo** [comment]
Ok I tested it with your fix and it's working as intended. Thanks a lot! 
I'm gonna close my PR, my solution was way more convoluted than just removing a "=" aha... ^^'

**Comment by asagi4** [comment]
I tested another refactoring but it breaks PerpNegAG. Oh well, good enough
